simple express app added
recognitionone/civ-clicker-timer-1 pull request #13
Opened 2019-05-27 15:18 UTC by recognitionone

2019-05-28 13:01 UTC, mika1111 requested changes

2019-05-28 13:01 UTC, mika1111 commented on app.js
> +app.get('/', (req, res) => res.send('Hello World!'))
I prefer index.html send :)

2019-05-28 13:01 UTC, mika1111 commented on package.json
> +  "dependencies": {
Add start script that will start server

2019-06-04 09:24 UTC, mika1111 requested changes

2019-06-04 09:24 UTC, mika1111 commented on hellonode.js
> +//Load HTTP module
Usuń wszystkie pliki związane z hallo world z expressa, zostawmy chwilowo tylko server.js

2019-06-04 09:24 UTC, mika1111 commented on package.json
> +    "lint": "eslint src",
Nice :)

2019-06-04 09:24 UTC, mika1111 commented on server.js
> +app.get('/test', (req, res) => res.sendFile(path.join(__dirname, './index.html')))
Nie pod test tylko pod root

2019-06-04 09:24 UTC, mika1111 commented on server.js
> +app.use('/assets-dog', express.static('assets'));
zmieniłabym na assets

2019-06-05 14:08 UTC, mika1111 commented on views/app.js
> +var createError = require('http-errors');
view folder is also to be removed

2019-06-06 13:20 UTC, recognitionone commented on hellonode.js
> +//Load HTTP module
ok

2019-06-06 13:21 UTC, recognitionone commented on server.js
> +app.get('/test', (req, res) => res.sendFile(path.join(__dirname, './index.html')))
ok

2019-06-06 13:22 UTC, recognitionone commented on views/app.js
> +var createError = require('http-errors');
ok

2019-06-06 15:25 UTC, merged