semi-working second timer
recognitionone/civ-clicker-timer-1 pull request #8
Opened 2019-05-17 14:27 UTC by recognitionone

2019-05-20 14:31 UTC, mika1111 requested changes

2019-05-20 14:31 UTC, mika1111 commented on view.js
>  		this.pauseButton = document.getElementById("pauseButton");
You should create second View for this

2019-05-20 14:31 UTC, mika1111 commented on model.js
> +
color is view not model

2019-05-23 17:20 UTC, mika1111 approved these changes

2019-05-23 17:20 UTC, closed without merging

2019-05-23 17:20 UTC, recognitionone commented
Not needed